### ISSUE TITLE
[all] Performance instrumentation and optimization

### ISSUE THREAD

**Issue by ArjunBhuptani** [connext/indra#1178]
Tracking the following:
- [x] Build max tps benchmarking tooling: https://github.com/connext/indra/issues/899
- [x] Allow finalized state to be passed into uninstall: https://github.com/connext/indra/issues/1180
- [x] Reduce 1 roundtrip from install: https://github.com/connext/indra/issues/1181
- [x] Optimize JSON serialization: https://github.com/connext/indra/issues/1182
- [x] Cache DB queries: https://github.com/connext/indra/issues/1183
- [x] Queue improvements
- [x] Pure-evm: https://github.com/connext/indra/pull/1235
- [x] Stored procedure calls: https://github.com/connext/indra/pull/1235
- [x] Cache json objects: https://github.com/connext/indra/pull/1235
- [ ] Benchmark max tps #1223

**Comment by ArjunBhuptani** [comment]
https://github.com/connext/indra/issues/1223 is still pending but going to close this tracking issue for now. We can create a followup issue(s) when we benchmark throughput and do our next round of performance optimizations
