### ISSUE TITLE
[cf-core] Recover from state divergence using SYNC

### ISSUE THREAD

**Issue by ArjunBhuptani** [connext/indra#1249]
There's a class of errors we're seeing (usually `validating signer...`) that are related to the two channel partners ending up at different states because of a failed protocol.

While we can work on some of the underlying causes for these issues, the reality is that state divergence could happen due to something as unpredictable as a dropped network packet.

We should catch these errors when they happen in the protocol and attempt a quick SYNC to recover before legitimately failing. This way, clients can resume operations even if they aren't necessarily going to disconnect/reconnect to explicitly run the sync protocol.

- [x] #1251 Sync should skip queue
- [x] #1253 Make sync more interactive to reduce payload size and only sync the diff
- [x] #1250 Try/Catch the protocol and attempt a sync on validating signer errors
