### ISSUE TITLE
[ card ] Tracker: Making Dai Card more usable as a reference implementation

### ISSUE THREAD

**Issue by ArjunBhuptani** [connext/indra#620]
Meta-issue to make the Dai Card more usable as a reference implementation. Includes all issues associated with Card UI changes and refactors. Should *not* include Dai Card bugs.

- [ ] Add collateralization stoplight indicator (formerly: https://github.com/ConnextProject/indra/issues/363)
- [ ] Add transaction history (formerly: https://github.com/ConnextProject/indra/issues/434)
- [ ] Detect and show if walletconnected signer is offline (formerly: https://github.com/ConnextProject/indra/issues/477)
- [ ] Polish UI (formerly: https://github.com/ConnextProject/indra/issues/567)
- [ ] Refactoring Connext functionality into separate files so that they can be decoupled from the UI

**Comment by ArjunBhuptani** [comment]
Closing for now and we can revisit when we want to properly spec out changes here
